- moz-extensions/src/email/resolve/ResolveComments.php
See https://bugzilla.mozilla.org/show_bug.cgi?id=1690681#c2
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1690681
Supersedes https://github.com/mozilla-services/phabricator-extensions/pull/70
Verified by @mitchhentges at https://github.com/mozilla-services/phabricator-extensions/pull/70#issuecomment-880066377
> Bug 1690681: Generate absolute URLs in emails

- .circleci/config.yml
Currently, CI is trying to build the `cryptography` package
(needed by `docker-compose`) from scratch. It's failing due to
the Rust compiler being missing.
However, we don't need to compile `cryptography` if we use the
prebuilt "wheel", which was being ignored because the `wheel`
package wasn't installed.
> Bug 1735635: Use Python 3.7 to ensure wheel usage

- README.md
Passing `?admin` as a query string parameter only works from the
`Login with BMO` page, so clarify the readme to include this
information. Looking at `webroot/rsrc/js/PhabricatorBMOAuth.js`
the query string just re-reoutes to `/auth/login/password:self`, so
also recommend connecting there directly.
> Bug 1738698: update admin panel login url

- Dockerfile
This version works better with my IDE. The default port
was changed from `9000` to `9003` in the new version and
a few config variables were renamed. We also add a log file
for debugging the debugger at `/tmp/xdebug.log`.
> Bug 1737601: upgrade `xdebug` to version 3.1.1

- docker-compose.yml
Add the `moz-extensions/` directory as a Docker
volume and mount that volume into the test container.
This makes `docker-compose run test_phab` use the
code local to the working directory allowing for
faster iteration when testing.
We also unset `restart-failure` in the test environment
as this causes the container to restart when any test
fails, however the container can't restart and hangs
around.
> Bug 1738776: put moz-extensions directory into a volume and mount into the test environment

- moz-extensions/src/email/adapter/PhabricatorUserStore.php
`PhabricatorPeopleQuery()` fails when `withPHIDs([])` is called with
an empty list.
We can avoid this failure by immediately returnin `[]` if the `$PHIDs`
list is empty.
> Bug 1739625: Skip Phab API when filtering by an empty list of PHIDs

- moz-extensions/src/email/FeedForEmailQueryAPIMethod.php
- moz-extensions/src/email/resolve/ResolveCodeChange.php
Determine if an "updated" event has caused differences in its changesets
by comparing against the previous diff's changesets.
Phabricator's `DifferentialChangeset->hasSameEffectAs(...)` function
compares the updated file's overall hash, which is great for most file
types (binary, image, etc).
However, for text files, we want to separate earlier-patch-changes from
current-patch-changes, and only send "revision-updated" emails for the
latter. We do this by comparing our two changesets, and only considering
them different if the "current-patch-line-changes" differ, ignoring
background changes to the file.
> Bug 1751482: Don't send "revision-updated" event if no local changes

- moz-extensions/src/applications/transactions/commentaction/PhabricatorUpdateUpliftCommentAction.php
- moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php
- webroot/rsrc/js/phuix/PHUIXFormControl.js
This commit adds interactions with Bugzilla when submitting an
uplift request form on Phabricator. To do this we change the
uplift request comment action from a standard textarea populated
with remarkup for the entire request, into a form with inputs
for each question in the form. We add a custom `form` PHUIXControlType
which takes a spec with a single `questions` field to populate
the values in the form.
We change the type of `DifferentialUpliftRequestCustomField::value`
from a string to a mapping array in all usages, and only convert
the mapping to a string when modifying and accessing from internal
storage. The beta uplift questions array is changed to a mapping of
`questions => defaults` for initial form population. We add a function
`getRemarkup` which converts the field mapping …
> Bug 1754076: make `Request Uplift` interact with Bugzilla

- hgext/differentiator.py
Previously we referenced `.arcconfig` to determine the callsign
for the given repo. Instead we check the location of `repo.root`
for an ID number which we reference against the ID value from
a search against `diffusion.repository.search`.
> Bug 1758000: use repo root and Phabricator repo IDs to retrieve callsign

- hgext/differentiator.py
`pathlib` doesn't work with bytes paths, so we need to decode
`repo.root` before creating the `Path` object.
While we are here, update the docstring to reflect the new
behaviour of the function and use the correct `%d` string
formatting operator.
> Bug 1758000: decode `repo.root` to `str` before passing to `Path`

- hgext/differentiator.py
We had incorrect type annotations on both callsign
fetching functions, so changing one function to actually
return `str` resulted in inconsistent types when comparing
otherwise identical strings. Stop encoding the value of
`get_phab_server_callsign` and only encode to `bytes` once
we need to send the string off to Mercurial.
Also use a different variable name for the encoded JSON
`params` to avoid changing the type from `dict` and yielding
a warning from linters.
> Bug 1760933: return a `str` from `get_phab_server_callsign`

- moz-extensions/src/email/resolve/ResolveCodeChange.php
The early `return false` was likely causing an email to be omitted if
the first changeset checked had no changes.
> Bug 1765394: Remove extraneous "return false"

- moz-extensions/src/applications/transactions/commentaction/PhabricatorUpdateUpliftCommentAction.php
- moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php
- webroot/rsrc/css/phui/phui-form-view.css
- webroot/rsrc/js/phuix/PHUIXFormControl.js
Make the uplift request form use the `display: table` CSS
style to improve the appearance of the form. Change yes/no
answers in the form from a checkbox to a dropdown selection.
Add better validation of the form submission to server-side
processing.
> Bug 1764136: improve styling of uplift request form

- src/infrastructure/markup/syntax/highlighter/PhutilPygmentsSyntaxHighlighter.php
in mozilla-central, in most case .h file is C++ code, and highlighting it as C++ code won't harm even if it's C code.
> Bug 1681067 - Treat .h file as C++.

- src/applications/differential/controller/DifferentialRevisionViewController.php
- webroot/rsrc/css/phui/phui-header-view.css
This is dirty hack that directly modifies the code that's not BMO-specific.
If this is not acceptable, I'll look into make it more generic, like comment markup.
Also, for some reason, a link in the header has almost same color as the header itself (`#464C5C` vs `#000000`),
and it's hard to notice it's a link, so I added extra rule to make the link more visible.
> Bug 1472174 - Linkify the bug number in the commit message in the revision page.

- src/infrastructure/markup/blockrule/PhutilRemarkupCodeBlockRule.php
Phabricator uses remarkup for comment markup, and it supports `lang=cpp` style option to enable syntax highlighting for the fenced code block.
Bugzilla and Matrix uses markdown (or maybe variant?), and Searchfox has a feature to copy a code block with Markdown-style (https://bugzilla.mozilla.org/show_bug.cgi?id=1769936), that uses just `cpp` to specify the language.
This patch adds fallback path for the case that code block rule doesn't detect `lang=cpp` style options, to use the `cpp` style.
To avoid unexpected result, the fallback happens only when it's in the same line as the backticks, followed by newline.
> Bug 1772684 - Support Markdown style language syntax for fenced code block.

- src/applications/differential/storage/DifferentialRevision.php
This change will help Lando calculate stack graph without making
repeated requests to the `edge.search` endpoint. A similar approach is
already used in Phabricator when loading the revision page.
> Bug 1787517: include stack dependencies in revision

- src/applications/differential/conduit/DifferentialCreateCommentConduitAPIMethod.php
To restore the functionality of `attach_inlines`, I implemented the following changes:
- Reverts commit 397648855f8bc272db1876da8ce2254d3da82fb9
- Copy the `loadUnsubmittedInlineComments` function from https://github.com/mozilla-conduit/phabricator/blob/397648855f8bc272db1876da8ce2254d3da82fb9/src/applications/differential/query/DifferentialTransactionQuery.php#L10-L53
- Comment out the section of `loadUnsubmittedInlineComments` that uses the `getContentForEdit` method because it was removed
> Bug 1873965 - Revert changes that made the `attach_inlines` parameter to `differential.createcomment` a no-op

- src/applications/differential/view/DifferentialChangesetDetailView.php
- webroot/rsrc/css/application/differential/changeset-view.css
Ported from Phorge:
https://we.phorge.it/D25757
> Bug 1916935 - Add Copy file path button to file header bar in Differential/Diffusion

- moz-extensions/src/lando/events/LandoLinkEventListener.php
Graying out the button indicates to the user that they should not click it,
when it is suggested to do so in documentation for submitting uplift
requests.
> Bug 1918751 - stop disabling "View Stack in Lando" for non-Accepted revisions

- src/applications/harbormaster/step/HarbormasterHTTPRequestBuildStepImplementation.php
Bug [1944522](https://bugzilla.mozilla.org/show_bug.cgi?id=1944522)
This PR adds an option to the Harbormaster HTTP Build Step to send an extra `Content-Type` header.
The current behaviour is preserved by default: no `Content-Type` header is sent.
I was able to test these changes locally, querying my own machine through a public IP from the docker container.
Using a  [debug server](https://gist.githubusercontent.com/phrawzty/62540f146ee5e74ea1ab/raw/8e079bf6230341f1abedbda119570248777a2208/3serv.py), I logged the headers sent by Phabricator when triggering manually a build plan:
```
Accept: */*
Content-Type: application/json;test-bastien
Accept-Encoding: gzip
Content-Length: 0
```
> Bug 1944522 - Add Content-Type header option in Harbormaster HTTP Build step

- moz-extensions/src/email/model/EmailRevisionLanded.php
- moz-extensions/src/email/resolve/ResolveRevisionStatus.php
- src/applications/differential/controller/DifferentialDiffCreateController.php
The `View Stack in Lando` button was updated to use the new
Lando URL, but a few places in the codebase are still using
the old `lando-ui.url` setting. Use `lando.url` in all remaining
places in the codebase.
> Bug 1955021: use new Lando URL for links in emails

- .circleci/config.yml
- .github/workflows/build-and-push.yaml
This PR adds a Github Action to build and push images on commits to the `main`/`master` branch to the new Google Artifact Registry.
I have not translated the test steps from the existing CircleCI configuration. This will be left to the maintainers of the project to implement as they prefer.
* [SVCSE-3411](https://mozilla-hub.atlassian.net/browse/SVCSE-3411)
> chore(ci): Add build and push Github Action.

- moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php
Mark `shouldAppearInEditView` as `true` in the `DifferentialUpliftRequestCustomField`
extension.
> Bug 1988566 - uplift request transaction is no longer available in `differential.revision.edit` API
